import "../styles/globals.scss";
import { Metadata } from 'next';
import Theme from "../styles/theme";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Theme>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Theme>
  )
}
